### ISSUE TITLE
Linux compilation on Manjaro

### ISSUE THREAD

**Issue by nifker** [AtomicGameEngine/AtomicGameEngine#555]
Im getting this error: 
In file included from /home/user/Desktop/AtomicGameEngine/Source/ThirdParty/TurboBadger/tb_renderer.h:12:0,
                 from /home/user/Desktop/AtomicGameEngine/Source/ThirdParty/TurboBadger/tb_renderer.cpp:6:
/home/user/Desktop/AtomicGameEngine/Source/ThirdParty/TurboBadger/tb_linklist.h: In Konstruktor »tb::TBLink::TBLink()«:
/home/user/Desktop/AtomicGameEngine/Source/ThirdParty/TurboBadger/tb_linklist.h:72:21: Fehler: »nullptr« wurde in diesem Gültigkeitsbereich nicht definiert
     TBLink() : prev(nullptr), next(nullptr), linklist(nullptr) {}
                     ^
/home/user/Desktop/AtomicGameEngine/Source/ThirdParty/TurboBadger/tb_linklist.h: In Konstruktor »tb::TBLinkList::TBLinkList()«:
/home/user/Desktop/AtomicGameEngine/Source/ThirdParty/TurboBadger/tb_linklist.h:96:26: Fehler: »nullptr« wurde in diesem Gültigkeitsbereich nicht definiert
     TBLinkList() : first(nullptr), last(nullptr), first_iterator(nullptr) {}
                          ^
Source/ThirdParty/TurboBadger/CMakeFiles/TurboBadger.dir/build.make:86: die Regel für Ziel „Source/ThirdParty/TurboBadger/CMakeFiles/TurboBadger.dir/tb_renderer.cpp.o“ scheiterte
make[2]: *** [Source/ThirdParty/TurboBadger/CMakeFiles/TurboBadger.dir/tb_renderer.cpp.o] Fehler 1
CMakeFiles/Makefile2:608: die Regel für Ziel „Source/ThirdParty/TurboBadger/CMakeFiles/TurboBadger.dir/all“ scheiterte
make[1]: *** [Source/ThirdParty/TurboBadger/CMakeFiles/TurboBadger.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

**Comment by Type1J** [comment]
Can you tell us what compiler you are using, and which version?

It looks like this is a compiler that doesn't know the C++11 nullptr keyword.

**Comment by nifker** [comment]
GCC 5.3

**Comment by Type1J** [comment]
That's an ultra new version (released last month), so I think that it's probably that you just need the '-std=c++11' compiler option, which probably should have been detected automatically.

Are you building for Linux? @CTrauma and @JoshEngebretson have been working on improving Linux build support, but I'm not sure which compilers were being used.

**Comment by nifker** [comment]
shall I append the argument to 'make' or to which command?

**Comment by Type1J** [comment]
To the topmost CMakeLists.txt, try adding

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

**Comment by nifker** [comment]
An error again:
Scanning dependencies of target AtomicPlayer
[ 93%] Building CXX object Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/AtomicPlayer.cpp.o
[ 93%] Linking CXX executable AtomicPlayer
../../AtomicJS/libAtomicJS.a(JSAtomic.cpp.o): In function `Atomic::jsapi_init_atomic(Atomic::JSVM*)':
JSAtomic.cpp:(.text+0x48e5): undefined reference to `Atomic::jsb_package_atomic_init(Atomic::JSVM*)'
../../AtomicPlayerJS/libAtomicPlayerJS.a(AtomicPlayerJS.cpp.o): In function `AtomicPlayer::jsapi_init_atomicplayer(Atomic::JSVM*)':
AtomicPlayerJS.cpp:(.text+0x14): undefined reference to `Atomic::jsb_package_atomicplayer_init(Atomic::JSVM*)'
collect2: Fehler: ld gab 1 als Ende-Status zurück
Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/build.make:123: die Regel für Ziel „Source/AtomicPlayer/Application/AtomicPlayer“ scheiterte
make[2]: *** [Source/AtomicPlayer/Application/AtomicPlayer] Fehler 1
CMakeFiles/Makefile2:1946: die Regel für Ziel „Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/all“ scheiterte
make[1]: *** [Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

**Comment by Type1J** [comment]
That looks like the JS binding didn't get generated. @JoshEngebretson, I'm not sure why this would happen, but did see it when I was cross compiling. @nifker, can you confirm that this is a build for (and on) Linux?

**Comment by CTrauma** [comment]
@nifker I have been building on Ubuntu Wily using GCC 5.2.1 without any problems.. Try running the Build_AtomicEditor.sh from the root of the repo and see what you get, that builds cleanly for me. I'm a bit short on time at the moment, but I'll watch this issue and I'm sure we can get you building.

**Comment by Type1J** [comment]
@nifker I reproduced all of your problems on a Linux VM. I think that I fixed all of them, but there are some notes:

Like @CTrauma said, you can use the Build_AtomicEditor.sh script to get a build, but if you want to use CMake directly, then make sure that you build the "GenerateScriptBindings" target before anything else. I think that there was a good reason that this wasn't made an explicit dependency of the final targets, even though they do depend on it.

From your newly made build directory:

    cmake ../AtomicGameEngine
    make GenerateScriptBindings
    make

If that doesn't work, yet, then wait until after #556 is merged, and try again.

**Comment by nifker** [comment]
ok compiled properly on manjaro and where can I find the binary file?

**Comment by JoshEngebretson** [comment]
Hi @nifker , the binary should be in the Artifacts/AtomicEditor folder

**Comment by nifker** [comment]
strangely the folder is empty. Ill just compile it again and we will se

**Comment by JoshEngebretson** [comment]
Are you using the Build_AtomicEditor.sh in the root folder?  If so, it should tell you where the editor was built to, the editor also has some resource requirements which are copied to the folder as part of the build.  I was able to build/run on Ubuntu 14.04 LTS, though was testing the #556 PR (which has some additional notes).  

If you aren't using the build scripts and are invoking CMake directly, the editor binary will be in the your build tree (probably under Source/AtomicEditor), make sure that you have specified -DATOMIC_DEV_BUILD=1 to cmake, so it uses the resources directly from the source tree.

**Comment by nifker** [comment]
It gives me some undefined references:
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/Atomic/Native/CSModuleUI.cpp.o: In function `csb_Atomic_UIView_Constructor':
CSModuleUI.cpp:(.text+0x19): undefined reference to `Atomic::NETCore::csContext_'
CSModuleUI.cpp:(.text+0x2f): undefined reference to `Atomic::NETCore::csContext_'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/Atomic/Native/CSModuleUI.cpp.o: In function `csb_Atomic_UISelectDropdown_Constructor':
CSModuleUI.cpp:(.text+0x83): undefined reference to `Atomic::NETCore::csContext_'
CSModuleUI.cpp:(.text+0x9f): undefined reference to `Atomic::NETCore::csContext_'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/Atomic/Native/CSModuleUI.cpp.o: In function `csb_Atomic_UIDragObject_Constructor':
CSModuleUI.cpp:(.text+0x12a): undefined reference to `Atomic::NETCore::csContext_'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/Atomic/Native/CSModuleUI.cpp.o:CSModuleUI.cpp:(.text+0x144): more undefined references to `Atomic::NETCore::csContext_' follow
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETCore.cpp.o: In function `csb_AtomicNET_NETCore_Constructor':
CSModuleNETCore.cpp:(.text+0xa17): undefined reference to `Atomic::NETCore::NETCore(Atomic::Context*)'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETCore.cpp.o: In function `csb_AtomicNET_NETCore_AddAssemblyLoadPath':
CSModuleNETCore.cpp:(.text+0xdb7): undefined reference to `Atomic::NETCore::AddAssemblyLoadPath(Atomic::String const&)'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETCore.cpp.o: In function `csb_AtomicNET_NETCore_GetContext':
CSModuleNETCore.cpp:(.text+0xe63): undefined reference to `Atomic::NETCore::csContext_'
CSModuleNETCore.cpp:(.text+0xe79): undefined reference to `Atomic::NETCore::csContext_'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETCore.cpp.o: In function `csb_AtomicNET_NETCore_Shutdown':
CSModuleNETCore.cpp:(.text+0xa41): undefined reference to `Atomic::NETCore::Shutdown()'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETCore.cpp.o: In function `csb_AtomicNET_NETCore_WaitForDebuggerConnect':
CSModuleNETCore.cpp:(.text+0xe51): undefined reference to `Atomic::NETCore::WaitForDebuggerConnect()'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSComponent_Constructor':
CSModuleNETScript.cpp:(.text+0x19): undefined reference to `Atomic::NETCore::csContext_'
CSModuleNETScript.cpp:(.text+0x2f): undefined reference to `Atomic::NETCore::csContext_'
CSModuleNETScript.cpp:(.text+0x47): undefined reference to `Atomic::CSComponent::CSComponent(Atomic::Context*)'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSComponent_SetComponentClassName':
CSModuleNETScript.cpp:(.text+0x407): undefined reference to `Atomic::CSComponent::SetComponentClassName(Atomic::String const&)'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSScriptObject_Constructor':
CSModuleNETScript.cpp:(.text+0x909): undefined reference to `Atomic::NETCore::csContext_'
CSModuleNETScript.cpp:(.text+0x91f): undefined reference to `Atomic::NETCore::csContext_'
CSModuleNETScript.cpp:(.text+0x937): undefined reference to `Atomic::CSScriptObject::CSScriptObject(Atomic::Context*)'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSManaged_Constructor':
CSModuleNETScript.cpp:(.text+0x979): undefined reference to `Atomic::NETCore::csContext_'
CSModuleNETScript.cpp:(.text+0x98f): undefined reference to `Atomic::NETCore::csContext_'
CSModuleNETScript.cpp:(.text+0x9a7): undefined reference to `Atomic::CSManaged::CSManaged(Atomic::Context*)'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSManaged_CSComponentCreate':
CSModuleNETScript.cpp:(.text+0x10c4): undefined reference to `Atomic::CSManaged::CSComponentCreate(Atomic::String const&, Atomic::String const&)'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSComponentAssembly_Constructor':
CSModuleNETScript.cpp:(.text+0x1219): undefined reference to `Atomic::NETCore::csContext_'
CSModuleNETScript.cpp:(.text+0x122f): undefined reference to `Atomic::NETCore::csContext_'
CSModuleNETScript.cpp:(.text+0x1247): undefined reference to `Atomic::CSComponentAssembly::CSComponentAssembly(Atomic::Context*)'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSComponentAssembly_CreateCSComponent':
CSModuleNETScript.cpp:(.text+0x15d9): undefined reference to `Atomic::CSComponentAssembly::CreateCSComponent(Atomic::String const&)'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSComponent_ApplyFieldValues':
CSModuleNETScript.cpp:(.text+0x91): undefined reference to `Atomic::CSComponent::ApplyFieldValues()'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSComponent_SetAssemblyFile':
CSModuleNETScript.cpp:(.text+0x8e1): undefined reference to `Atomic::CSComponent::SetAssemblyFile(Atomic::CSComponentAssembly*)'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSManaged_Initialize':
CSModuleNETScript.cpp:(.text+0x9d1): undefined reference to `Atomic::CSManaged::Initialize()'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSManaged_NETUpdate':
CSModuleNETScript.cpp:(.text+0x9e1): undefined reference to `Atomic::CSManaged::NETUpdate(float)'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSManaged_CSComponentApplyFields':
CSModuleNETScript.cpp:(.text+0x11e1): undefined reference to `Atomic::CSManaged::CSComponentApplyFields(Atomic::CSComponent*, Atomic::NETVariantMap*)'
CMakeFiles/AtomicPlayer.dir/__/__/__/Artifacts/Build/Source/Generated/LINUX/CSharp/Packages/AtomicNET/Native/CSModuleNETScript.cpp.o: In function `csb_AtomicNET_CSManaged_CSComponentCallMethod':
CSModuleNETScript.cpp:(.text+0x11f1): undefined reference to `Atomic::CSManaged::CSComponentCallMethod(unsigned int, Atomic::CSComponentMethod, float)'
collect2: Fehler: ld gab 1 als Ende-Status zurück
Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/build.make:799: die Regel für Ziel „Source/AtomicPlayer/Application/AtomicPlayer“ scheiterte
make[2]: *** [Source/AtomicPlayer/Application/AtomicPlayer] Fehler 1
CMakeFiles/Makefile2:1946: die Regel für Ziel „Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/all“ scheiterte
make[1]: *** [Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

**Comment by Type1J** [comment]
The above undefined references are fixed in #556.

**Comment by nifker** [comment]
how can I apply them?

**Comment by Type1J** [comment]
It's specifically https://github.com/Type1J/AtomicGameEngine/commit/c02fa511214d6acc9ac38469396840e1add86493

**Comment by Type1J** [comment]
@nifker You should be able to use revert those temporary changes and pull now: #556 is merged.

**Comment by JoshEngebretson** [comment]
I re-added the CI task to validate PR's on Linux with the new build improvements.   I also updated the Linux build instructions, these are confirmed to work on Ubuntu 14.04 LTS 64bit:

https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Building-the-Atomic-Editor-from-Source
