### ISSUE TITLE
Cant build on Ubuntu 14.04 64 bits

### ISSUE THREAD

**Issue by Murii** [AtomicGameEngine/AtomicGameEngine#19]
Description	Resource	Path	Location	Type
make[1]: *** [Source/ThirdParty/LibCpuId/CMakeFiles/LibCpuId.dir/all] Error 2	Atomic@BUILDATO		 	C/C++ Problem
conflicting types for ‘int64_t’	libcpuid_types.h	/Atomic@BUILDATO/[Source directory]/Source/ThirdParty/LibCpuId/src	line 55	C/C++ Problem
make[2]: *** [Source/ThirdParty/LibCpuId/CMakeFiles/LibCpuId.dir/src/libcpuid_util.c.o] Error 1	Atomic@BUILDATO		 	C/C++ Problem
previous declaration of ‘int64_t’ was here	Atomic@BUILDATO		line 197, external location: /usr/include/x86_64-linux-gnu/sys/types.h	C/C++ Problem
converting to non-pointer type ‘int’ from NULL [-Wconversion-null]	hull.cpp	/Atomic@BUILDATO/[Source directory]/Source/ThirdParty/StanHull	line 2590	C/C++ Problem
make: *** [all] Error 2	Atomic@BUILDATO		 	C/C++ Problem
Invalid project path: Include path not found (/home/vlad/Downloads/AtomicGameEngine-master/Source/ThirdParty/StanHull/include).	Atomic@BUILDATO		pathentry	Path Entry Problem

**Comment by JoshEngebretson** [comment]
Linux support for the Editor and Player is planned, though we don't currently have an ETA on them.

**Comment by JoshEngebretson** [comment]
Closing, as created issues for the Linux Player #21 and the Linux Editor #22
